### ISSUE TITLE
이슈는 아니고요 그냥 한번 남겨보고싶었어여

### ISSUE THREAD

**Issue by yoyooyoyoyo** [mrt1847-test/practice_automation#1]
이슈는 없는데여 그냥 한번 남겨보고싶었어여 추석에 한번 진행중인데 뭐가 문제인건지 pipenv 관련 인터프리터 설정이 잘 안되네여, 껄껄
회사 복귀하면 여쭤볼꼐여어어어

**Comment by mrt1847-test** [comment]
지원님 안녕하세요! 잘 지내시는지요
오랜만에 들어와서 최신화좀 하다가 보게 되었네요.....
제가 만든거에서는 pipenv 는 적용 안해도 되요
그냥 하시면 됩니다
뭐 또 궁금하신거 있으시면 언제든 물어봐 주세요 
언젠가 뵐 수 있었음 좋겠습니다....

**Comment by mrt1847-test** [comment]
> 이슈는 없는데여 그냥 한번 남겨보고싶었어여 추석에 한번 진행중인데 뭐가 문제인건지 pipenv 관련 인터프리터 설정이 잘 안되네여, 껄껄 회사 복귀하면 여쭤볼꼐여어어어

**Comment by yoyooyoyoyo** [comment]
준회님 잘 지내고 계신가요.. 저 입사한 회사에서 엄청 스트레스받으면서 일하고있구욥 우는일도 다반사입니다….ㅠㅠ 다음에 기회되면 만나서
썰 풀고싶어요ㅠㅠ
